# Generated by Django 4.2.9 on 2026-06-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_caption', models.TextField(blank=True, default='')),
                ('instagram_caption', models.TextField(blank=True, default='')),
                ('facebook_caption', models.TextField(blank=True, default='')),
                ('pinterest_caption', models.TextField(blank=True, default='')),
                ('twitter_caption', models.TextField(blank=True, default='')),
                ('threads_caption', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('public_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('caption_style', models.CharField(blank=True, default='', max_length=50)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Post queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('threads', 'Threads')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='poster.postqueue')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
