/**
 * Affiliate link utilities for the frontend.
 * In production, these links would be generated by the backend.
 */

const AFFILIATE_IDS = {
  amazon: process.env.REACT_APP_AMAZON_ASSOCIATE_ID || '',
  meesho: process.env.REACT_APP_MEESHO_ID || '',
  flipkart: process.env.REACT_APP_FLIPKART_ID || '',
};

const BASE_REDIRECT = process.env.REACT_APP_REDIRECT_BASE || 'https://fashionbazzer-backend.onrender.com/r';

export function buildAffiliateLink(productUrl, platform, productId) {
  // In production, call the backend to generate a tracked link
  return `${BASE_REDIRECT}/${productId}_${platform}`;
}

export function getPlatformCommission(platform) {
  const rates = {
    meesho: { min: 5, max: 15 },
    amazon: { min: 4, max: 8 },
    flipkart: { min: 5, max: 10 },
    myntra: { min: 3, max: 8 },
    ajio: { min: 5, max: 12 },
  };
  return rates[platform] || { min: 3, max: 10 };
}

export function estimateEarnings(clicks, commissionRate = 0.08, avgOrderValue = 600, conversionRate = 0.02) {
  const purchases = Math.floor(clicks * conversionRate);
  const revenue = purchases * avgOrderValue;
  const earnings = revenue * commissionRate;
  return {
    purchases,
    revenue,
    earnings: Math.round(earnings),
  };
}
