# Generated by Django 4.2.9 on 2026-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('platform', models.CharField(help_text='meesho, amazon, flipkart, myntra, ajio', max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('co-ord', 'Co-ord Sets'), ('y2k', 'Y2K Dresses'), ('bodycon', 'Bodycon Mini Dresses'), ('cottagecore', 'Cottagecore Maxi Dresses'), ('indo-western', 'Indo-Western Fusion'), ('athleisure', 'Athleisure Dresses'), ('cut-out', 'Cut-out Dresses'), ('wrap', 'Printed Wrap Dresses'), ('other', 'Other')], default='other', max_length=50)),
                ('product_url', models.URLField(max_length=1000)),
                ('affiliate_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_trending', models.BooleanField(default=False)),
                ('ai_tagline', models.TextField(blank=True, default='')),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_trending'], name='products_pr_platfor_9c812b_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx')],
            },
        ),
    ]
