# Generated by Django 4.2.9 on 2026-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price_stale',
            field=models.BooleanField(default=False, help_text='Flagged when prices look suspicious (0% discount, missing rating)'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_price_updated',
            field=models.DateTimeField(blank=True, help_text='When price data was last successfully confirmed', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_price_stale'], name='products_pr_is_pric_b286fb_idx'),
        ),
    ]
