# Generated by Django 4.2.9 on 2026-06-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter/X'), ('threads', 'Threads')], max_length=20, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('posts_today', models.IntegerField(default=0)),
                ('posts_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('affiliate_url', models.URLField(max_length=1000)),
                ('platform', models.CharField(max_length=50)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='products.product')),
            ],
            options={
                'ordering': ['-click_count'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_platform', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_id', models.CharField(blank=True, default='', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='products.product')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=1000)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tracker.trackedlink')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['short_code'], name='tracker_tra_short_c_99fba3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['platform'], name='tracker_tra_platfor_bcd298_idx'),
        ),
    ]
